export default {
  THEME_INIT: "THEME_INIT",
  THEME_CHANGE: "THEME_CHANGE",
  ON_SHOW_CUSTOM_THEME_View: "ON_SHOW_CUSTOM_THEME_View",
  // SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
  POPULAR_REFRESH: "POPULAR_REFRESH",
  LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL",
  LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS",

  INIT_LANGUAGE: "INIT_LANGUAGE",
  CHANGE_CUSTOM_KEY: "CHANGE_CUSTOM_KEY",
}
